# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-weather-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-weather-app
  template:
    metadata:
      labels:
        app: react-weather-app
    spec:
      imagePullSecrets:
        - name: ghcr-secret  # Reference the secret you created
      containers:
        - name: react-weather-app
          image: ghcr.io/dispatch-yt/whether-app:latest # Use your private image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-weather-app
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: react-weather-app
